import { ExpectationOperator } from './operator';

/* Generated by @n1k1t/unit-generator */
it('extractNestedSchema should return null for empty schema', () => {
  class TestOperator extends ExpectationOperator<any, any> {
    async match() {
      return true;
    }
    async manipulate(context: any) {
      return context;
    }
    get tags() {
      return {};
    }
    public testExtractNestedSchema(schema: any) {
      return this.extractNestedSchema(schema);
    }
  }
  const operator = new TestOperator({} as any, {} as any);
  expect(operator.testExtractNestedSchema({})).toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('extractNestedSchema should return first key and value', () => {
  class TestOperator extends ExpectationOperator<any, any> {
    async match() {
      return true;
    }
    async manipulate(context: any) {
      return context;
    }
    get tags() {
      return {};
    }
    public testExtractNestedSchema(schema: any) {
      return this.extractNestedSchema(schema);
    }
  }
  const operator = new TestOperator({} as any, {} as any);
  expect(operator.testExtractNestedSchema({ $set: { a: 1 }, $has: true })).toEqual({ key: '$set', nested: { a: 1 } });
});

/* Generated by @n1k1t/unit-generator */
it('compileExecHandler should execute function with utils', async () => {
  class TestOperator extends ExpectationOperator<any, any> {
    async match() {
      return true;
    }
    async manipulate(context: any) {
      return context;
    }
    get tags() {
      return {};
    }
    public testCompileExecHandler(raw: any, provide: any) {
      return this.compileExecHandler(raw, provide);
    }
  }
  const operator = new TestOperator({} as any, {} as any);
  const raw = (utils: any) => utils.mode;
  const handler = operator.testCompileExecHandler(raw, ['utils']);
  const result = await handler('match', {} as any);
  expect(result).toBe('match');
});

/* Generated by @n1k1t/unit-generator */
it('compileExecHandler should execute string with utils', async () => {
  class TestOperator extends ExpectationOperator<any, any> {
    async match() {
      return true;
    }
    async manipulate(context: any) {
      return context;
    }
    get tags() {
      return {};
    }
    public testCompileExecHandler(raw: any, provide: any) {
      return this.compileExecHandler(raw, provide);
    }
  }
  const operator = new TestOperator({} as any, {} as any);
  const raw = 'mode';
  const handler = operator.testCompileExecHandler(raw, ['utils']);
  const result = await handler('manipulate', {} as any);
  expect(result).toBe('manipulate');
});

/* Generated by @n1k1t/unit-generator */
it('compileExecHandler should execute string with payload', async () => {
  class TestOperator extends ExpectationOperator<any, any> {
    async match() {
      return true;
    }
    async manipulate(context: any) {
      return context;
    }
    get tags() {
      return {};
    }
    public testCompileExecHandler(raw: any, provide: any) {
      return this.compileExecHandler(raw, provide);
    }
  }
  const operator = new TestOperator({} as any, {} as any);
  const raw = 'payload * 2';
  const handler = operator.testCompileExecHandler(raw, ['payload']);
  const result = await handler('match', {} as any, 21);
  expect(result).toBe(42);
});

/* Generated by @n1k1t/unit-generator */
it('compileExecHandler should handle curried function', async () => {
  class TestOperator extends ExpectationOperator<any, any> {
    async match() {
      return true;
    }
    async manipulate(context: any) {
      return context;
    }
    get tags() {
      return {};
    }
    public testCompileExecHandler(raw: any, provide: any) {
      return this.compileExecHandler(raw, provide);
    }
  }
  const operator = new TestOperator({} as any, {} as any);
  const raw = () => (utils: any) => utils.mode;
  const handler = operator.testCompileExecHandler(raw, ['utils']);
  const result = await handler('match', {} as any);
  expect(result).toBe('match');
});

/* Generated by @n1k1t/unit-generator */
it('compileExecHandler should provide faker with seed from context', async () => {
  class TestOperator extends ExpectationOperator<any, any> {
    async match() {
      return true;
    }
    async manipulate(context: any) {
      return context;
    }
    get tags() {
      return {};
    }
    public testCompileExecHandler(raw: any, provide: any) {
      return this.compileExecHandler(raw, provide);
    }
  }
  const operator = new TestOperator({} as any, {} as any);
  const raw = (utils: any) => utils.faker.number.int();
  const handler = operator.testCompileExecHandler(raw, ['utils']);
  const res1 = await handler('match', { seed: 123 } as any);
  const res2 = await handler('match', { seed: 123 } as any);
  expect(res1).toBe(res2);
});

/* Generated by @n1k1t/unit-generator */
it('compileExecHandler should provide lodash in utils', async () => {
  class TestOperator extends ExpectationOperator<any, any> {
    async match() {
      return true;
    }
    async manipulate(context: any) {
      return context;
    }
    get tags() {
      return {};
    }
    public testCompileExecHandler(raw: any, provide: any) {
      return this.compileExecHandler(raw, provide);
    }
  }
  const operator = new TestOperator({} as any, {} as any);
  const raw = (utils: any) => utils._.isNumber(123);
  const handler = operator.testCompileExecHandler(raw, ['utils']);
  const result = await handler('match', {} as any);
  expect(result).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('compileExecHandler should provide dayjs in utils', async () => {
  class TestOperator extends ExpectationOperator<any, any> {
    async match() {
      return true;
    }
    async manipulate(context: any) {
      return context;
    }
    get tags() {
      return {};
    }
    public testCompileExecHandler(raw: any, provide: any) {
      return this.compileExecHandler(raw, provide);
    }
  }
  const operator = new TestOperator({} as any, {} as any);
  const raw = (utils: any) => utils.d('2023-01-01').year();
  const handler = operator.testCompileExecHandler(raw, ['utils']);
  const result = await handler('match', {} as any);
  expect(result).toBe(2023);
});

/* Generated by @n1k1t/unit-generator */
it('compileExecHandler should provide rxjs in utils', async () => {
  class TestOperator extends ExpectationOperator<any, any> {
    async match() {
      return true;
    }
    async manipulate(context: any) {
      return context;
    }
    get tags() {
      return {};
    }
    public testCompileExecHandler(raw: any, provide: any) {
      return this.compileExecHandler(raw, provide);
    }
  }
  const operator = new TestOperator({} as any, {} as any);
  const raw = (utils: any) => typeof utils.rx.of === 'function';
  const handler = operator.testCompileExecHandler(raw, ['utils']);
  const result = await handler('match', {} as any);
  expect(result).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('compileExecHandler should provide context in utils', async () => {
  class TestOperator extends ExpectationOperator<any, any> {
    async match() {
      return true;
    }
    async manipulate(context: any) {
      return context;
    }
    get tags() {
      return {};
    }
    public testCompileExecHandler(raw: any, provide: any) {
      return this.compileExecHandler(raw, provide);
    }
  }
  const operator = new TestOperator({} as any, {} as any);
  const context = { foo: 'bar' };
  const raw = (utils: any) => utils.context.foo;
  const handler = operator.testCompileExecHandler(raw, ['utils']);
  const result = await handler('match', context as any);
  expect(result).toBe('bar');
});

/* Generated by @n1k1t/unit-generator */
it('compileExecHandler should provide logger in utils', async () => {
  class TestOperator extends ExpectationOperator<any, any> {
    async match() {
      return true;
    }
    async manipulate(context: any) {
      return context;
    }
    get tags() {
      return {};
    }
    public testCompileExecHandler(raw: any, provide: any) {
      return this.compileExecHandler(raw, provide);
    }
  }
  const operator = new TestOperator({} as any, {} as any);
  const raw = (utils: any) => !!utils.logger;
  const handler = operator.testCompileExecHandler(raw, ['utils']);
  const result = await handler('match', {} as any);
  expect(result).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('compileExecHandler should provide meta in utils', async () => {
  class TestOperator extends ExpectationOperator<any, any> {
    async match() {
      return true;
    }
    async manipulate(context: any) {
      return context;
    }
    get tags() {
      return {};
    }
    public testCompileExecHandler(raw: any, provide: any) {
      return this.compileExecHandler(raw, provide);
    }
  }
  const operator = new TestOperator({} as any, {} as any);
  const raw = (utils: any) => !!utils.meta;
  const handler = operator.testCompileExecHandler(raw, ['utils']);
  const result = await handler('match', {} as any);
  expect(result).toBe(true);
});
