import { buildExpectationContext } from '../__utils__';
import { ExpectationsStorage } from './storage';
import { Expectation } from './expectation';

it('should not match with empty storage', async () => {
  const storage = new ExpectationsStorage({ group: 'test' });

  expect(await storage.match(buildExpectationContext())).toBeNull();
});

it('should match with 1 expectation', async () => {
  const storage = new ExpectationsStorage({ group: 'test' });
  const { expectation } = <{ expectation: Expectation }>storage.register({
    schema: {
      request: { $has: { $location: 'path', $value: '/foo/bar/baz' } },
    },
  });

  expect((await storage.match(buildExpectationContext()))?.id).toEqual(expectation.id);
});

it('should not match with 1 expectation', async () => {
  const storage = new ExpectationsStorage({ group: 'test' });
  storage.register({
    schema: {
      request: { $has: { $location: 'path', $value: '/foo' } },
    },
  });

  expect(await storage.match(buildExpectationContext())).toBeNull();
});

it('should match with 2 expectations', async () => {
  const storage = new ExpectationsStorage({ group: 'test' });
  storage.register({
    schema: {
      request: { $has: { $location: 'path', $value: '/foo/bar' } },
    },
  });
  const { expectation } = <{ expectation: Expectation }>storage.register({
    schema: {
      request: { $has: { $location: 'method', $valueAnyOf: ['GET', 'POST'] } },
    },
  });

  expect((await storage.match(buildExpectationContext()))?.id).toEqual(expectation.id);
});

it('should not match with 2 expectations', async () => {
  const storage = new ExpectationsStorage({ group: 'test' });
  storage.register({
    schema: {
      request: { $has: { $location: 'path', $value: '/foo/bar' } },
    },
  });
  storage.register({
    schema: {
      request: { $has: { $location: 'method', $valueAnyOf: ['GET'] } },
    },
  });

  expect(await storage.match(buildExpectationContext())).toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('should copy all expectations from the source storage when extend is called', () => {
  const storage = new ExpectationsStorage({ group: 'g1' });
  const otherStorage = new ExpectationsStorage({ group: 'g2' });
  const expectation = { id: 'exp-1' } as any;
  otherStorage.set('exp-1', expectation);
  storage.extend(otherStorage);
  expect(storage.get('exp-1')).toBe(expectation);
});

/* Generated by @n1k1t/unit-generator */
it('should return the current storage instance when extend is called', () => {
  const storage = new ExpectationsStorage({ group: 'g1' });
  const otherStorage = new ExpectationsStorage({ group: 'g2' });
  const result = storage.extend(otherStorage);
  expect(result).toBe(storage);
});

/* Generated by @n1k1t/unit-generator */
it('should return an error status and reasons when registration validation fails', () => {
  const storage = new ExpectationsStorage({ group: 'g1' });
  const errors = [{ message: 'error' }] as any;
  const spy = jest.spyOn(Expectation, 'build').mockReturnValue({
    validate: () => errors,
  } as any);
  const result = storage.register({} as any);
  expect(result).toEqual({ status: 'ERROR', reasons: errors });
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should return the expectation when it matches the context transport and request', async () => {
  const storage = new ExpectationsStorage({ group: 'g1' });
  const expectation = {
    isEnabled: true,
    transports: ['http'],
    request: { match: jest.fn().mockResolvedValue(<never>true) },
    id: 'exp-1',
  } as any;
  storage.set('exp-1', expectation);
  const context = buildExpectationContext();
  const result = await storage.match(context);
  expect(result).toBe(expectation);
});
