import { parsePayload, serializePayload } from './index';

/* Generated by @n1k1t/unit-generator */
it('should parse xml payload from Buffer when expected type is xml', () => {
  expect(parsePayload(Buffer.from('<root>test</root>'), 'xml')).toEqual({
    type: 'xml',
    data: { root: 'test' },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should parse xml payload from string when expected type is xml', () => {
  expect(parsePayload('<root>test</root>', 'xml')).toEqual({
    type: 'xml',
    data: { root: 'test' },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should parse json payload from Buffer when it is a valid JSON object', () => {
  expect(parsePayload(Buffer.from('{"a":1}'))).toEqual({
    type: 'json',
    data: { a: 1 },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should parse json payload from string when it is a valid JSON object', () => {
  expect(parsePayload('{"a":1}')).toEqual({
    type: 'json',
    data: { a: 1 },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should parse json payload from Buffer when it is a valid JSON array', () => {
  expect(parsePayload(Buffer.from('[1,2]'))).toEqual({
    type: 'json',
    data: [1, 2],
  });
});

/* Generated by @n1k1t/unit-generator */
it('should parse plain payload from Buffer when it is a valid JSON but not an object', () => {
  expect(parsePayload(Buffer.from('123'))).toEqual({
    type: 'plain',
    data: 123,
  });
});

/* Generated by @n1k1t/unit-generator */
it('should parse plain payload from Buffer when it is invalid JSON', () => {
  expect(parsePayload(Buffer.from('not-json'))).toEqual({
    type: 'plain',
    data: 'not-json',
  });
});

/* Generated by @n1k1t/unit-generator */
it('should parse json payload when input is an object', () => {
  expect(parsePayload({ a: 1 })).toEqual({
    type: 'json',
    data: { a: 1 },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should parse plain payload when input is a number', () => {
  expect(parsePayload(42)).toEqual({
    type: 'plain',
    data: 42,
  });
});

/* Generated by @n1k1t/unit-generator */
it('should parse plain payload when input is null', () => {
  expect(parsePayload(null)).toEqual({
    type: 'plain',
    data: null,
  });
});

/* Generated by @n1k1t/unit-generator */
it('should serialize json payload to Buffer', () => {
  expect(serializePayload('json', { a: 1 })).toEqual(Buffer.from('{"a":1}'));
});

/* Generated by @n1k1t/unit-generator */
it('should serialize plain payload to Buffer', () => {
  expect(serializePayload('plain', 'hello')).toEqual(Buffer.from('hello'));
});

/* Generated by @n1k1t/unit-generator */
it('should serialize xml payload to Buffer', () => {
  expect(serializePayload('xml', { root: 'test' }).toString()).toEqual('<root>test</root>');
});

/* Generated by @n1k1t/unit-generator */
it('should handle null payload in serializePayload for json type', () => {
  expect(serializePayload('json', null)).toEqual(Buffer.from('null'));
});

/* Generated by @n1k1t/unit-generator */
it('should handle null payload in serializePayload for plain type', () => {
  expect(serializePayload('plain', null)).toEqual(Buffer.from(''));
});

/* Generated by @n1k1t/unit-generator */
it('should handle null payload in serializePayload for xml type', () => {
  expect(serializePayload('xml', null)).toEqual(Buffer.from(''));
});

/* Generated by @n1k1t/unit-generator */
it('should serialize plain payload with 0 to Buffer containing "0"', () => {
  expect(serializePayload('plain', 0)).toEqual(Buffer.from('0'));
});

/* Generated by @n1k1t/unit-generator */
it('should serialize json payload with undefined to empty Buffer', () => {
  expect(serializePayload('json', undefined)).toEqual(Buffer.from(''));
});
