import { Type } from '@n1k1t/typebox';
import { extractValidationMetaContext, validate, UseValidation } from './validation';

/* Generated by @n1k1t/unit-generator */
it('should return null when extracting context from a class without validation', () => {
  class TestClass {}
  expect(extractValidationMetaContext(TestClass)).toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('should return a context when extracting from a class with UseValidation', () => {
  class TestClass {
    @UseValidation(Type.String())
    prop!: string;
  }
  expect(extractValidationMetaContext(TestClass)).not.toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('should return an empty array when validating an instance of a class without validation', () => {
  class TestClass {}
  const instance = new TestClass();
  expect(validate(instance)).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('should return validation errors when instance data is invalid', () => {
  class TestClass {
    @UseValidation(Type.Number())
    prop!: number;
  }
  const instance = new TestClass();
  (instance as any).prop = 'not a number';
  expect(validate(instance).length).toBeGreaterThan(0);
});

/* Generated by @n1k1t/unit-generator */
it('should return an empty array when instance data is valid', () => {
  class TestClass {
    @UseValidation(Type.String())
    prop!: string;
  }
  const instance = new TestClass();
  instance.prop = 'valid string';
  expect(validate(instance)).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('should accumulate multiple properties in the validation schema', () => {
  class TestClass {
    @UseValidation(Type.String())
    a!: string;
    @UseValidation(Type.Number())
    b!: number;
  }
  const context = extractValidationMetaContext(TestClass);
  expect(context?.properties.size).toBe(2);
});

/* Generated by @n1k1t/unit-generator */
it('should validate correctly when using schema references', () => {
  const StringRef = Type.String({ $id: 'StringRef' });
  class TestClass {
    @UseValidation(Type.Ref(StringRef))
    prop!: string;
  }
  const instance = new TestClass();
  instance.prop = 'test';
  expect(validate(instance, [StringRef])).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('should return a ValueError object with correct path when validation fails', () => {
  class TestClass {
    @UseValidation(Type.String())
    prop!: string;
  }
  const instance = new TestClass();
  (instance as any).prop = 123;
  expect(validate(instance)[0].path).toBe('/prop');
});
