import { SystemContainersStorage, SystemHistoryStorage, SystemProvider } from './system';
import { RequestContextSnapshot } from '../context';
import { Container } from '../containers';
import { Provider } from './model';
import { History } from '../history';

/* Generated by @n1k1t/unit-generator */
it('should restore containers and store them with group prefix', () => {
  const storage = new SystemContainersStorage({ group: 'test-group' });
  const dump = {
    payloads: [{ foo: 'bar' }],
    containers: [
      {
        key: 'my-key',
        group: 'test-group',
        payload: 0,
        ttl: 100,
        timestamp: 123456789,
      },
    ],
  };
  storage.restore(dump);
  expect(storage.find('test-group:my-key')?.payload).toEqual({ foo: 'bar' });
});

/* Generated by @n1k1t/unit-generator */
it('should restore history items from plain list', () => {
  const storage = new SystemHistoryStorage({ group: 'test-group', limit: 10 });
  const plainHistory: any = {
    id: 'history-id-1',
    group: 'test-group',
    status: 'completed',
    timestamp: 123456789,
    meta: {
      tags: {
        transport: 'http',
        incoming: { path: '/test', method: 'GET' },
        outgoing: { status: 200 },
      },
      metrics: { duration: 10 },
    },
    snapshot: {
      transport: 'http',
      event: 'request',
      flags: {},
      cache: { isEnabled: false },
      state: {},
      incoming: {
        type: 'json',
        path: '/test',
        method: 'GET',
        headers: {},
      },
      outgoing: {
        type: 'json',
        status: 200,
        headers: {},
      },
      messages: [],
    },
  };
  storage.restore([plainHistory]);
  expect(storage.get('history-id-1')?.status).toBe('completed');
});

/* Generated by @n1k1t/unit-generator */
it('should restore history items with expectation', () => {
  const storage = new SystemHistoryStorage({ group: 'test-group', limit: 10 });
  const plainHistory: any = {
    id: 'history-id-2',
    group: 'test-group',
    status: 'completed',
    timestamp: 123456789,
    meta: {
      tags: {
        transport: 'http',
        incoming: { path: '/test', method: 'GET' },
        outgoing: { status: 200 },
      },
      metrics: { duration: 10 },
    },
    expectation: {
      id: 'exp-1',
      group: 'test-group',
      name: 'TestExpectation',
      isEnabled: true,
      schema: {
        request: { $exec: () => true },
      },
    },
    snapshot: {
      transport: 'http',
      event: 'request',
      flags: {},
      cache: { isEnabled: false },
      state: {},
      incoming: {
        type: 'json',
        path: '/test',
        method: 'GET',
        headers: {},
      },
      outgoing: {
        type: 'json',
        status: 200,
        headers: {},
      },
      messages: [],
    },
  };
  storage.restore([plainHistory]);
  expect(storage.get('history-id-2')?.expectation?.id).toBe('exp-1');
});

/* Generated by @n1k1t/unit-generator */
it('should restore history items with forwarded snapshot', () => {
  const storage = new SystemHistoryStorage({ group: 'test-group', limit: 10 });
  const plainHistory: any = {
    id: 'history-id-3',
    group: 'test-group',
    status: 'completed',
    timestamp: 123456789,
    meta: {
      tags: {
        transport: 'http',
        incoming: { path: '/test', method: 'GET' },
        outgoing: { status: 200 },
      },
      metrics: { duration: 10 },
    },
    snapshot: {
      transport: 'http',
      event: 'request',
      flags: {},
      cache: { isEnabled: false },
      state: {},
      incoming: {
        type: 'json',
        path: '/test',
        method: 'GET',
        headers: {},
      },
      outgoing: {
        type: 'json',
        status: 200,
        headers: {},
      },
      messages: [],
      forwarded: {
        schema: { url: 'http://forward-url' },
        messages: [],
        incoming: {
          type: 'json',
          path: '/test',
          method: 'GET',
          headers: {},
          dataRaw: [102, 111, 111],
        },
        outgoing: {
          type: 'json',
          status: 200,
          headers: {},
          dataRaw: [98, 97, 114],
        },
      },
    },
  };
  storage.restore([plainHistory]);
  expect(storage.get('history-id-3')?.snapshot.forwarded?.incoming.dataRaw).toEqual(Buffer.from([102, 111, 111]));
});

/* Generated by @n1k1t/unit-generator */
it('should distribute history to target provider and delete from system provider', () => {
  const systemProvider = SystemProvider.build({ group: 'system' });
  const targetProvider = Provider.build({ group: 'target-group' });
  const history = History.build({
    id: 'hist-1',
    group: 'target-group',
    snapshot: RequestContextSnapshot.build({
      transport: 'http',
      flags: {},
      storage: systemProvider.storages.containers,
      incoming: { type: 'json', path: '/test', method: 'GET', headers: {}, query: {} },
      outgoing: { type: 'json', status: 200, headers: {} },
    }),
  });
  systemProvider.storages.history.set(history.id, history);
  systemProvider.distribute(targetProvider);
  expect(systemProvider.storages.history.has('hist-1')).toBe(false);
});

/* Generated by @n1k1t/unit-generator */
it('should register distributed history in target provider', () => {
  const systemProvider = SystemProvider.build({ group: 'system' });
  const targetProvider = Provider.build({ group: 'target-group' });
  const history = History.build({
    id: 'hist-2',
    group: 'target-group',
    snapshot: RequestContextSnapshot.build({
      transport: 'http',
      flags: {},
      storage: systemProvider.storages.containers,
      incoming: { type: 'json', path: '/test', method: 'GET', headers: {}, query: {} },
      outgoing: { type: 'json', status: 200, headers: {} },
    }),
  });
  systemProvider.storages.history.set(history.id, history);
  systemProvider.distribute(targetProvider);
  expect(targetProvider.storages.history.has('hist-2')).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('should distribute container to target provider and delete from system provider', () => {
  const systemProvider = SystemProvider.build({ group: 'system' });
  const targetProvider = Provider.build({ group: 'target-group' });
  const container = Container.build({
    key: 'cont-1',
    group: 'target-group',
    payload: { x: 1 },
    ttl: 100,
    timestamp: Date.now(),
  });
  systemProvider.storages.containers.set('cont-1', container);
  systemProvider.distribute(targetProvider);
  expect(systemProvider.storages.containers.find('cont-1')).toBeUndefined();
});

/* Generated by @n1k1t/unit-generator */
it('should register distributed container in target provider', () => {
  const systemProvider = SystemProvider.build({ group: 'system' });
  const targetProvider = Provider.build({ group: 'target-group' });
  const container = Container.build({
    key: 'cont-2',
    group: 'target-group',
    payload: { x: 1 },
    ttl: 100,
    timestamp: Date.now(),
  });
  systemProvider.storages.containers.set('cont-2', container);
  systemProvider.distribute(targetProvider);
  expect(targetProvider.storages.containers.find('cont-2')?.payload).toEqual({ x: 1 });
});

/* Generated by @n1k1t/unit-generator */
it('should not distribute history of a different group', () => {
  const systemProvider = SystemProvider.build({ group: 'system' });
  const targetProvider = Provider.build({ group: 'target-group' });
  const history = History.build({
    id: 'hist-3',
    group: 'other-group',
    snapshot: RequestContextSnapshot.build({
      transport: 'http',
      flags: {},
      storage: systemProvider.storages.containers,
      incoming: { type: 'json', path: '/test', method: 'GET', headers: {}, query: {} },
      outgoing: { type: 'json', status: 200, headers: {} },
    }),
  });
  systemProvider.storages.history.set(history.id, history);
  systemProvider.distribute(targetProvider);
  expect(systemProvider.storages.history.has('hist-3')).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('should not distribute container of a different group', () => {
  const systemProvider = SystemProvider.build({ group: 'system' });
  const targetProvider = Provider.build({ group: 'target-group' });
  const container = Container.build({
    key: 'cont-3',
    group: 'other-group',
    payload: { x: 1 },
    ttl: 100,
    timestamp: Date.now(),
  });
  systemProvider.storages.containers.set('cont-3', container);
  systemProvider.distribute(targetProvider);
  expect(systemProvider.storages.containers.find('cont-3')?.payload).toEqual({ x: 1 });
});

/* Generated by @n1k1t/unit-generator */
it('should build SystemProvider instance', () => {
  const provider = SystemProvider.build({ group: 'system' });
  expect(provider).toBeInstanceOf(SystemProvider);
});
