import { faker } from '@faker-js/faker';
import { RequestContextSnapshot } from '../../models';
import { HistoryStorage } from './storage';
import { History } from './model';
import config from '../../../config';

// Test generated using Keploy
test('test_registerHistory_withoutExistingHistory_createsValidHistory', () => {
  const storage = new HistoryStorage({ group: 'test-group' });
  const historyData = { snapshot: { incoming: {}, outgoing: {} } };
  const result = storage.register(<any>historyData);
  expect(result).toBeInstanceOf(History);
  expect(result.group).toBe('test-group');
  expect(result.snapshot).toEqual(historyData.snapshot);
});

// Test generated using Keploy
test('test_unregisterHistory_removesHistoryFromStorage', () => {
  const storage = new HistoryStorage({ group: 'test-group' });
  const historyInstance = new History(<any>{ id: '1', snapshot: { incoming: {}, outgoing: {} } });
  storage.register(historyInstance);
  expect(storage.size).toBe(1);
  storage.unregister(historyInstance);
  expect(storage.size).toBe(0);
});

// Test generated using Keploy
test('test_registerHistory_exceedsLimit_removesOldestEntry', () => {
  const mockConfig = { get: () => ({ limit: 2 }) };
  jest.spyOn(config, 'get').mockImplementation(<any>mockConfig.get);

  const storage = new HistoryStorage({ group: 'test-group' });
  const history1 = new History(<any>{ id: '1', snapshot: { incoming: {}, outgoing: {} } });
  const history2 = new History(<any>{ id: '2', snapshot: { incoming: {}, outgoing: {} } });
  const history3 = new History(<any>{ id: '3', snapshot: { incoming: {}, outgoing: {} } });

  storage.register(history1);
  storage.register(history2);
  expect(storage.size).toBe(2);
  storage.register(history3);
  expect(storage.size).toBe(2);
  expect(storage.has('1')).toBe(false); // oldest entry should be removed
});

/* Generated by @n1k1t/unit-generator */
it('should return the newly registered history item when the limit is exceeded', () => {
  const storage = new HistoryStorage({ group: faker.word.sample() });
  const history1 = History.build({
    status: 'registered',
    group: storage['configuration'].group,
    snapshot: RequestContextSnapshot.build(<any>{ incoming: {}, outgoing: {}, transport: faker.word.sample() }),
  });
  const history2 = History.build({
    status: 'registered',
    group: storage['configuration'].group,
    snapshot: RequestContextSnapshot.build(<any>{ incoming: {}, outgoing: {}, transport: faker.word.sample() }),
  });

  storage.register(history1);
  const registeredHistory = storage.register(history2);

  expect(registeredHistory).toBe(history2);
});

/* Generated by @n1k1t/unit-generator */
it('should keep the newly registered history item in storage when the limit is exceeded', () => {
  const storage = new HistoryStorage({ group: faker.word.sample() });
  const history1 = History.build({
    status: 'registered',
    group: storage['configuration'].group,
    snapshot: RequestContextSnapshot.build(<any>{ incoming: {}, outgoing: {}, transport: faker.word.sample() }),
  });
  const history2 = History.build({
    status: 'registered',
    group: storage['configuration'].group,
    snapshot: RequestContextSnapshot.build(<any>{ incoming: {}, outgoing: {}, transport: faker.word.sample() }),
  });

  storage.register(history1);
  storage.register(history2);

  expect(storage.has(history2.id)).toBeTruthy();
});
