import { ValidationError } from '../errors';
import { Expectation } from '../../expectations';

import method from './expectations.update.method';
import config from '../../config';

import * as utils from '../utils';

/* Generated by @n1k1t/unit-generator */
it('should call instance.request in remote handler', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: 'result' } }) };
  const remote = method.compile('remote', instance as any);
  await remote({ id: '123', set: {} });
  expect(instance.request).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with correct id in remote handler', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: 'result' } }) };
  const remote = method.compile('remote', instance as any);
  await remote({ id: '123', set: {} });
  expect(instance.request).toHaveBeenCalledWith(
    expect.objectContaining({ data: expect.objectContaining({ id: '123' }) }),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with PUT method in remote handler', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: 'result' } }) };
  const remote = method.compile('remote', instance as any);
  await remote({ id: '123', set: {} });
  expect(instance.request).toHaveBeenCalledWith(expect.objectContaining({ method: 'PUT' }));
});

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with correct URL in remote handler', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: 'result' } }) };
  const remote = method.compile('remote', instance as any);
  jest.spyOn(config, 'get').mockReturnValue({ system: <any>{ root: '/root' } });
  await remote({ id: '123', set: {} });
  expect(instance.request).toHaveBeenCalledWith(expect.objectContaining({ url: '/root/expectations' }));
});

/* Generated by @n1k1t/unit-generator */
it('should return response.data.data in remote handler', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: 'result' } }) };
  const remote = method.compile('remote', instance as any);
  const result = await remote({ id: '123', set: {} });
  expect(result).toBe('result');
});

/* Generated by @n1k1t/unit-generator */
it('should call handleRequestError when instance.request fails in remote handler', async () => {
  const error = new Error('fail');
  const instance = { request: jest.fn().mockRejectedValue(error) };
  const remote = method.compile('remote', instance as any);
  const spy = jest.spyOn(utils, 'handleRequestError').mockImplementation(() => {
    throw new Error('handled');
  });
  await expect(remote({ id: '123', set: {} })).rejects.toThrow('handled');
});

/* Generated by @n1k1t/unit-generator */
it('should return null in onsite handler if expectation is not found', async () => {
  const provider = { storages: { expectations: { get: jest.fn().mockReturnValue(null) } } };
  const onsite = method.compile('onsite', provider as any);
  const result = await onsite({ id: '123', set: {} });
  expect(result).toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('should throw ValidationError in onsite handler if validation fails', async () => {
  const found = { id: '123', name: 'old', meta: {}, configuration: {}, toPlain: () => ({}), validate: () => [] };
  const provider = { storages: { expectations: { get: jest.fn().mockReturnValue(found) } } };
  const onsite = method.compile('onsite', provider as any);
  jest.spyOn(Expectation, 'build').mockReturnValue({ validate: () => ['error'] } as any);
  await expect(onsite({ id: '123', set: {} })).rejects.toThrow(ValidationError);
});

/* Generated by @n1k1t/unit-generator */
it('should update storage in onsite handler', async () => {
  const found = { id: '123', name: 'old', meta: {}, configuration: {}, toPlain: () => ({}), validate: () => [] };
  const provider = {
    storages: { expectations: { get: jest.fn().mockReturnValue(found), set: jest.fn() } },
    server: { exchanges: { io: { publish: jest.fn() } } },
  };
  const onsite = method.compile('onsite', provider as any);
  const mockExpectation = { validate: () => [], toPlain: () => ({ id: '123' }) };
  jest.spyOn(Expectation, 'build').mockReturnValue(mockExpectation as any);
  await onsite({ id: '123', set: {} });
  expect(provider.storages.expectations.set).toHaveBeenCalledWith('123', mockExpectation);
});

/* Generated by @n1k1t/unit-generator */
it('should publish expectation:updated event in onsite handler', async () => {
  const found = { id: '123', name: 'old', meta: {}, configuration: {}, toPlain: () => ({}), validate: () => [] };
  const provider = {
    storages: { expectations: { get: jest.fn().mockReturnValue(found), set: jest.fn() } },
    server: { exchanges: { io: { publish: jest.fn() } } },
  };
  const onsite = method.compile('onsite', provider as any);
  const plain = { id: '123', name: 'updated' };
  jest.spyOn(Expectation, 'build').mockReturnValue({ validate: () => [], toPlain: () => plain } as any);
  await onsite({ id: '123', set: {} });
  expect(provider.server.exchanges.io.publish).toHaveBeenCalledWith('expectation:updated', plain);
});

/* Generated by @n1k1t/unit-generator */
it('should return updated.toPlain() in onsite handler', async () => {
  const found = { id: '123', name: 'old', meta: {}, configuration: {}, toPlain: () => ({}), validate: () => [] };
  const provider = {
    storages: { expectations: { get: jest.fn().mockReturnValue(found), set: jest.fn() } },
    server: { exchanges: { io: { publish: jest.fn() } } },
  };
  const onsite = method.compile('onsite', provider as any);
  const plain = { id: '123', name: 'updated' };
  jest.spyOn(Expectation, 'build').mockReturnValue({ validate: () => [], toPlain: () => plain } as any);
  const result = await onsite({ id: '123', set: {} });
  expect(result).toEqual(plain);
});

/* Generated by @n1k1t/unit-generator */
it('should use source array instead of merging in onsite handler', async () => {
  const found = {
    id: '123',
    name: 'old',
    meta: {},
    configuration: { transports: ['http'] },
    toPlain: () => ({}),
    validate: () => [],
  };
  const provider = {
    storages: { expectations: { get: jest.fn().mockReturnValue(found), set: jest.fn() } },
    server: { exchanges: { io: { publish: jest.fn() } } },
  };
  const onsite = method.compile('onsite', provider as any);
  const spy = jest.spyOn(Expectation, 'build');
  await onsite({ id: '123', set: { transports: ['ws'] } });
  expect(spy).toHaveBeenCalledWith(expect.objectContaining({ transports: ['ws'] }));
});

/* Generated by @n1k1t/unit-generator */
it('should preserve original name in onsite handler', async () => {
  const found = { id: '123', name: 'original', meta: {}, configuration: {}, toPlain: () => ({}), validate: () => [] };
  const provider = {
    storages: { expectations: { get: jest.fn().mockReturnValue(found), set: jest.fn() } },
    server: { exchanges: { io: { publish: jest.fn() } } },
  };
  const onsite = method.compile('onsite', provider as any);
  const spy = jest.spyOn(Expectation, 'build');
  await onsite({ id: '123', set: { name: 'new' } as any });
  expect(spy).toHaveBeenCalledWith(expect.objectContaining({ name: 'original' }));
});

/* Generated by @n1k1t/unit-generator */
it('should preserve original meta in onsite handler', async () => {
  const found = {
    id: '123',
    name: 'original',
    meta: { tags: { a: 1 } },
    configuration: {},
    toPlain: () => ({}),
    validate: () => [],
  };
  const provider = {
    storages: { expectations: { get: jest.fn().mockReturnValue(found), set: jest.fn() } },
    server: { exchanges: { io: { publish: jest.fn() } } },
  };
  const onsite = method.compile('onsite', provider as any);
  const spy = jest.spyOn(Expectation, 'build');
  await onsite({ id: '123', set: { meta: { tags: { b: 2 } } } as any });
  expect(spy).toHaveBeenCalledWith(expect.objectContaining({ meta: { tags: { a: 1 } } }));
});

/* Generated by @n1k1t/unit-generator */
it('should preserve original id in onsite handler', async () => {
  const found = { id: '123', name: 'original', meta: {}, configuration: {}, toPlain: () => ({}), validate: () => [] };
  const provider = {
    storages: { expectations: { get: jest.fn().mockReturnValue(found), set: jest.fn() } },
    server: { exchanges: { io: { publish: jest.fn() } } },
  };
  const onsite = method.compile('onsite', provider as any);
  const spy = jest.spyOn(Expectation, 'build');
  await onsite({ id: '123', set: { id: '456' } as any });
  expect(spy).toHaveBeenCalledWith(expect.objectContaining({ id: '123' }));
});

/* Generated by @n1k1t/unit-generator */
it('should call prepareExpectationBodyToRequest in remote handler', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: 'result' } }) };
  const body = { id: '123', set: { name: 'new name' } };
  const remote = method.compile('remote', instance as any);
  const spy = jest.spyOn(utils, 'prepareExpectationBodyToRequest');
  await remote(body);
  expect(spy).toHaveBeenCalledWith(body.set);
});
