import expectationsDeleteMethod from './expectations.delete.method';

/* Generated by @n1k1t/unit-generator */
it('should return null from remote registration', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: null }) } as any;
  const remote = expectationsDeleteMethod.compile('remote', instance);
  const result = await remote({ ids: ['1'] });
  expect(result).toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with DELETE method in remote registration', async () => {
  const request = jest.fn().mockResolvedValue({ data: null });
  const instance = { request } as any;
  const remote = expectationsDeleteMethod.compile('remote', instance);
  await remote({ ids: ['1'] });
  expect(request).toHaveBeenCalledWith(expect.objectContaining({ method: 'DELETE' }));
});

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with correct url in remote registration', async () => {
  const request = jest.fn().mockResolvedValue({ data: null });
  const instance = { request } as any;
  const remote = expectationsDeleteMethod.compile('remote', instance);
  await remote({ ids: ['1'] });
  expect(request).toHaveBeenCalledWith(expect.objectContaining({ url: expect.stringContaining('/expectations') }));
});

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with provided data in remote registration', async () => {
  const request = jest.fn().mockResolvedValue({ data: null });
  const instance = { request } as any;
  const body = { ids: ['id1', 'id2'] };
  const remote = expectationsDeleteMethod.compile('remote', instance);
  await remote(body);
  expect(request).toHaveBeenCalledWith(expect.objectContaining({ data: body }));
});

/* Generated by @n1k1t/unit-generator */
it('should return null from onsite registration', async () => {
  const provider = { storages: { expectations: { delete: jest.fn(), clear: jest.fn() } } } as any;
  const onsite = expectationsDeleteMethod.compile('onsite', provider);
  const result = await onsite({ ids: ['1'] });
  expect(result).toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('should call provider.storages.expectations.delete for each id in onsite registration', async () => {
  const deleteMock = jest.fn();
  const provider = { storages: { expectations: { delete: deleteMock } } } as any;
  const onsite = expectationsDeleteMethod.compile('onsite', provider);
  await onsite({ ids: ['id1', 'id2'] });
  expect(deleteMock).toHaveBeenCalledTimes(2);
});

/* Generated by @n1k1t/unit-generator */
it('should call provider.storages.expectations.delete with correct id in onsite registration', async () => {
  const deleteMock = jest.fn();
  const provider = { storages: { expectations: { delete: deleteMock } } } as any;
  const onsite = expectationsDeleteMethod.compile('onsite', provider);
  await onsite({ ids: ['id1'] });
  expect(deleteMock).toHaveBeenCalledWith('id1');
});

/* Generated by @n1k1t/unit-generator */
it('should call provider.storages.expectations.clear in onsite registration when no ids provided', async () => {
  const clearMock = jest.fn();
  const provider = { storages: { expectations: { clear: clearMock } } } as any;
  const onsite = expectationsDeleteMethod.compile('onsite', provider);
  await onsite({});
  expect(clearMock).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should call provider.storages.expectations.clear in onsite registration when body is null', async () => {
  const clearMock = jest.fn();
  const provider = { storages: { expectations: { clear: clearMock } } } as any;
  const onsite = expectationsDeleteMethod.compile('onsite', provider);
  await onsite(null as any);
  expect(clearMock).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should call provider.storages.expectations.clear in onsite registration when body is undefined', async () => {
  const clearMock = jest.fn();
  const provider = { storages: { expectations: { clear: clearMock } } } as any;
  const onsite = expectationsDeleteMethod.compile('onsite', provider);
  await onsite(undefined as any);
  expect(clearMock).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should not call clear in onsite registration when ids is an empty array', async () => {
  const clearMock = jest.fn();
  const provider = { storages: { expectations: { clear: clearMock } } } as any;
  const onsite = expectationsDeleteMethod.compile('onsite', provider);
  await onsite({ ids: [] });
  expect(clearMock).not.toHaveBeenCalled();
});
