import expectationsGroupUpdate from './expectations-group.update.method';
import config from '../../config';

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with the correct URL in remote handler', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: {} } }) };
  const handler = expectationsGroupUpdate.compile('remote', instance as any);
  await handler({ set: { isEnabled: true } } as any);
  expect(instance.request).toHaveBeenCalledWith(
    expect.objectContaining({
      url: `${config.get('routes').system.root}/expectations/group`,
    }),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with PUT method in remote handler', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: {} } }) };
  const handler = expectationsGroupUpdate.compile('remote', instance as any);
  await handler({ set: { isEnabled: true } } as any);
  expect(instance.request).toHaveBeenCalledWith(
    expect.objectContaining({
      method: 'PUT',
    }),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with the provided body as data in remote handler', async () => {
  const body = { set: { isEnabled: true } };
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: {} } }) };
  const handler = expectationsGroupUpdate.compile('remote', instance as any);
  await handler(body as any);
  expect(instance.request).toHaveBeenCalledWith(
    expect.objectContaining({
      data: body,
    }),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should return the data from the response in remote handler', async () => {
  const expectedData = [{ id: '1' }];
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: expectedData } }) };
  const handler = expectationsGroupUpdate.compile('remote', instance as any);
  const result = await handler({ set: { isEnabled: true } } as any);
  expect(result).toEqual(expectedData);
});

/* Generated by @n1k1t/unit-generator */
it('should update the isEnabled property of each expectation in onsite handler', async () => {
  const expectation = { isEnabled: false, toPlain: jest.fn().mockReturnValue({}) };
  const provider = {
    storages: { expectations: { values: () => [expectation] } },
    server: { exchanges: { io: { publish: jest.fn() } } },
  };
  const handler = expectationsGroupUpdate.compile('onsite', provider as any);
  await handler({ set: { isEnabled: true } } as any);
  expect(expectation.isEnabled).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('should call toPlain on each expectation in onsite handler', async () => {
  const expectation = { isEnabled: false, toPlain: jest.fn().mockReturnValue({}) };
  const provider = {
    storages: { expectations: { values: () => [expectation] } },
    server: { exchanges: { io: { publish: jest.fn() } } },
  };
  const handler = expectationsGroupUpdate.compile('onsite', provider as any);
  await handler({ set: { isEnabled: true } } as any);
  expect(expectation.toPlain).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should publish an update event for each expectation in onsite handler', async () => {
  const plain = { id: '1', isEnabled: true };
  const expectation = { isEnabled: false, toPlain: jest.fn().mockReturnValue(plain) };
  const publish = jest.fn();
  const provider = {
    storages: { expectations: { values: () => [expectation] } },
    server: { exchanges: { io: { publish } } },
  };
  const handler = expectationsGroupUpdate.compile('onsite', provider as any);
  await handler({ set: { isEnabled: true } } as any);
  expect(publish).toHaveBeenCalledWith('expectation:updated', plain);
});

/* Generated by @n1k1t/unit-generator */
it('should return an array of plain expectations in onsite handler', async () => {
  const plain = { id: '1', isEnabled: true };
  const expectation = { isEnabled: false, toPlain: jest.fn().mockReturnValue(plain) };
  const provider = {
    storages: { expectations: { values: () => [expectation] } },
    server: { exchanges: { io: { publish: jest.fn() } } },
  };
  const handler = expectationsGroupUpdate.compile('onsite', provider as any);
  const result = await handler({ set: { isEnabled: true } } as any);
  expect(result).toEqual([plain]);
});

/* Generated by @n1k1t/unit-generator */
it('should return an empty array if there are no expectations in onsite handler', async () => {
  const provider = {
    storages: { expectations: { values: () => [] } },
    server: { exchanges: { io: { publish: jest.fn() } } },
  };
  const handler = expectationsGroupUpdate.compile('onsite', provider as any);
  const result = await handler({ set: { isEnabled: true } } as any);
  expect(result).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('should not throw if provider.server is undefined in onsite handler', async () => {
  const expectation = { isEnabled: false, toPlain: jest.fn().mockReturnValue({}) };
  const provider = {
    storages: { expectations: { values: () => [expectation] } },
    server: undefined,
  };
  const handler = expectationsGroupUpdate.compile('onsite', provider as any);
  const result = await handler({ set: { isEnabled: true } } as any);
  expect(result).toBeDefined();
});
