import method from './expectations.create.method';

/* Generated by @n1k1t/unit-generator */
it('should return response.data.data in remote handler', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: 'remote-result' } }) } as any;
  const remote = method.compile('remote', instance);
  const result = await remote({});
  expect(result).toEqual('remote-result');
});

/* Generated by @n1k1t/unit-generator */
it('should call provider.storages.expectations.register with body and group in onsite handler', async () => {
  const provider = {
    group: 'test-group',
    storages: {
      expectations: {
        register: jest.fn().mockReturnValue({ status: 'SUCCESS', expectation: { toPlain: () => ({}) } }),
      },
    },
  } as any;
  const body = { foo: 'bar' };
  const onsite = method.compile('onsite', provider);
  await onsite(body);
  expect(provider.storages.expectations.register).toHaveBeenCalledWith(
    expect.objectContaining({ foo: 'bar', group: 'test-group' }),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should throw ValidationError if registration status is ERROR in onsite handler', async () => {
  const provider = {
    group: 'test-group',
    storages: { expectations: { register: jest.fn().mockReturnValue({ status: 'ERROR', reasons: ['error-reason'] }) } },
  } as any;
  const onsite = method.compile('onsite', provider);
  await expect(onsite({})).rejects.toThrow();
});

/* Generated by @n1k1t/unit-generator */
it('should publish expectation:added event in onsite handler', async () => {
  const publish = jest.fn();
  const provider = {
    group: 'test-group',
    storages: {
      expectations: {
        register: jest.fn().mockReturnValue({ status: 'SUCCESS', expectation: { toPlain: () => 'plain-data' } }),
      },
    },
    server: { exchanges: { io: { publish } } },
  } as any;
  const onsite = method.compile('onsite', provider);
  await onsite({});
  expect(publish).toHaveBeenCalledWith('expectation:added', 'plain-data');
});

/* Generated by @n1k1t/unit-generator */
it('should return result.expectation.toPlain() in onsite handler', async () => {
  const provider = {
    group: 'test-group',
    storages: {
      expectations: {
        register: jest.fn().mockReturnValue({ status: 'SUCCESS', expectation: { toPlain: () => 'plain-data' } }),
      },
    },
    server: { exchanges: { io: { publish: jest.fn() } } },
  } as any;
  const onsite = method.compile('onsite', provider);
  const result = await onsite({});
  expect(result).toEqual('plain-data');
});

/* Generated by @n1k1t/unit-generator */
it('should not fail if provider.server is undefined in onsite handler', async () => {
  const provider = {
    group: 'test-group',
    storages: {
      expectations: {
        register: jest.fn().mockReturnValue({ status: 'SUCCESS', expectation: { toPlain: () => ({}) } }),
      },
    },
    server: undefined,
  } as any;
  const onsite = method.compile('onsite', provider);
  await expect(onsite({})).resolves.toBeDefined();
});
