import pingMethod from './ping.method';
import config from '../../config';

import * as utils from '../utils';

/* Generated by @n1k1t/unit-generator */
it('should return "pong" when onsite implementation is called', async () => {
  const handler = pingMethod.compile('onsite', {} as any);
  const result = await handler(undefined);
  expect(result).toBe('pong');
});

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with GET method in remote implementation', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: 'pong' } }) } as any;
  const handler = pingMethod.compile('remote', instance);
  await handler(undefined);
  expect(instance.request).toHaveBeenCalledWith(expect.objectContaining({ method: 'GET' }));
});

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with correct URL in remote implementation', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: 'pong' } }) } as any;
  const handler = pingMethod.compile('remote', instance);
  await handler(undefined);
  expect(instance.request).toHaveBeenCalledWith(
    expect.objectContaining({ url: `${config.get('routes').system.root}/ping` }),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should return data from response in remote implementation', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: 'pong' } }) } as any;
  const handler = pingMethod.compile('remote', instance);
  const result = await handler(undefined);
  expect(result).toBe('pong');
});

/* Generated by @n1k1t/unit-generator */
it('should call handleRequestError when request fails in remote implementation', async () => {
  const error = new Error('Network Error');
  const instance = { request: jest.fn().mockRejectedValue(error) } as any;
  const spy = jest.spyOn(utils, 'handleRequestError').mockImplementation(() => {
    throw new Error('Handled');
  });
  const handler = pingMethod.compile('remote', instance);
  await handler(undefined).catch(() => {});
  expect(spy).toHaveBeenCalledWith(error);
  spy.mockRestore();
});
