import { handleRequestError } from '../utils';

import providersCreateMethod from './providers.create.method';
import config from '../../config';

jest.mock('../utils', () => ({
  ...jest.requireActual('../utils'),
  handleRequestError: jest.fn().mockImplementation((err) => {
    throw err;
  }),
}));

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with the correct URL', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: {} } }) } as any;
  await providersCreateMethod.compile('remote', instance)({} as any);
  expect(instance.request).toHaveBeenCalledWith(
    expect.objectContaining({ url: `${config.get('routes').system.root}/providers` }),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with the POST method', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: {} } }) } as any;
  await providersCreateMethod.compile('remote', instance)({} as any);
  expect(instance.request).toHaveBeenCalledWith(expect.objectContaining({ method: 'POST' }));
});

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with the provided body as data', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: {} } }) } as any;
  const body = { name: 'test-provider' };
  await providersCreateMethod.compile('remote', instance)(body as any);
  expect(instance.request).toHaveBeenCalledWith(expect.objectContaining({ data: body }));
});

/* Generated by @n1k1t/unit-generator */
it('should return the data property from the response', async () => {
  const responseData = { id: 'provider-1' };
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: responseData } }) } as any;
  const result = await providersCreateMethod.compile('remote', instance)({} as any);
  expect(result).toEqual(responseData);
});

/* Generated by @n1k1t/unit-generator */
it('should call handleRequestError when the request fails', async () => {
  const error = new Error('Network Error');
  const instance = { request: jest.fn().mockRejectedValue(error) } as any;
  try {
    await providersCreateMethod.compile('remote', instance)({} as any);
  } catch (e) {
    // ignore
  }
  expect(handleRequestError).toHaveBeenCalledWith(error);
});
