import method from './providers.delete.method';
import config from '../../config';

import * as utils from '../utils';

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with correct url', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: null } }) } as any;
  await method.compile('remote', instance)({ group: 'test-group' });
  expect(instance.request).toHaveBeenCalledWith(
    expect.objectContaining({
      url: `${config.get('routes').system.root}/providers`,
    }),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with correct method', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: null } }) } as any;
  await method.compile('remote', instance)({ group: 'test-group' });
  expect(instance.request).toHaveBeenCalledWith(
    expect.objectContaining({
      method: 'DELETE',
    }),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should call instance.request with provided body', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: null } }) } as any;
  const body = { group: 'test-group' };
  await method.compile('remote', instance)(body);
  expect(instance.request).toHaveBeenCalledWith(
    expect.objectContaining({
      data: body,
    }),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should return data from response', async () => {
  const expectedData = { success: true };
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: expectedData } }) } as any;
  const result = await method.compile('remote', instance)({ group: 'test-group' });
  expect(result).toEqual(expectedData);
});

/* Generated by @n1k1t/unit-generator */
it('should call handleRequestError on request failure', async () => {
  const error = new Error('Request failed');
  const instance = { request: jest.fn().mockRejectedValue(error) } as any;
  const spy = jest.spyOn(utils, 'handleRequestError').mockImplementation(() => {
    throw new Error('Handled');
  });
  await method
    .compile(
      'remote',
      instance,
    )({ group: 'test-group' })
    .catch(() => {});
  expect(spy).toHaveBeenCalledWith(error);
});

/* Generated by @n1k1t/unit-generator */
it('should call config.get with "routes"', async () => {
  const instance = { request: jest.fn().mockResolvedValue({ data: { data: null } }) } as any;
  const spy = jest.spyOn(config, 'get');
  await method.compile('remote', instance)({ group: 'test-group' });
  expect(spy).toHaveBeenCalledWith('routes');
});
