import { faker } from '@faker-js/faker';
import { RequestMessage } from './message';

/* Generated by @n1k1t/unit-generator */
it('should set direction from constructor', () => {
  const msg = new RequestMessage({ direction: 'incoming', type: 'plain', data: 'test', raw: {} });
  expect(msg.direction).toBe('incoming');
});

/* Generated by @n1k1t/unit-generator */
it('should set type from constructor', () => {
  const msg = new RequestMessage({ direction: 'incoming', type: 'json', data: {}, raw: {} });
  expect(msg.type).toBe('json');
});

/* Generated by @n1k1t/unit-generator */
it('should set data from constructor', () => {
  const msg = new RequestMessage({ direction: 'incoming', type: 'plain', data: 'test-data', raw: {} });
  expect(msg.data).toBe('test-data');
});

/* Generated by @n1k1t/unit-generator */
it('should set default timestamp in constructor when not provided', () => {
  const msg = new RequestMessage({ direction: 'incoming', type: 'plain', data: 'test', raw: {} });
  expect(msg.timestamp).toBeGreaterThan(0);
});

/* Generated by @n1k1t/unit-generator */
it('should return true for matching type in is()', () => {
  const msg = new RequestMessage({ direction: 'incoming', type: 'json', data: {}, raw: {} });
  expect(msg.is('json')).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('should return false for non-matching type in is()', () => {
  const msg = new RequestMessage({ direction: 'incoming', type: 'json', data: {}, raw: {} });
  expect(msg.is('plain')).toBe(false);
});

/* Generated by @n1k1t/unit-generator */
it('should return the same buffer if data is a Buffer in serialize()', () => {
  const data = Buffer.from('test');
  const msg = new RequestMessage({ direction: 'incoming', type: 'plain', data, raw: {} });
  expect(msg.serialize()).toBe(data);
});

/* Generated by @n1k1t/unit-generator */
it('should serialize object data to JSON buffer in serialize()', () => {
  const data = { foo: 'bar' };
  const msg = new RequestMessage({ direction: 'incoming', type: 'json', data, raw: {} });
  expect(msg.serialize().toString()).toBe(JSON.stringify(data));
});

/* Generated by @n1k1t/unit-generator */
it('should serialize string data to Buffer in serialize()', () => {
  const msg = new RequestMessage({ direction: 'incoming', type: 'plain', data: 'test-string', raw: {} });
  expect(msg.serialize().toString()).toBe('test-string');
});

/* Generated by @n1k1t/unit-generator */
it('should return raw data length for incoming message size()', () => {
  const rawData = Buffer.from('raw-data');
  const msg = new RequestMessage({ direction: 'incoming', type: 'plain', data: 'data', raw: { data: rawData } });
  expect(msg.size()).toBe(8);
});

/* Generated by @n1k1t/unit-generator */
it('should return serialized length for outgoing message size()', () => {
  const msg = new RequestMessage({ direction: 'outgoing', type: 'plain', data: 'data', raw: {} });
  expect(msg.size()).toBe(4);
});

/* Generated by @n1k1t/unit-generator */
it('should create a new instance in clone()', () => {
  const msg = new RequestMessage({ direction: 'incoming', type: 'plain', data: 'test', raw: {} });
  const cloned = msg.clone();
  expect(cloned).not.toBe(msg);
});

/* Generated by @n1k1t/unit-generator */
it('should deep clone data when deep option is true in clone()', () => {
  const data = { a: { b: 1 } };
  const msg = new RequestMessage({ direction: 'incoming', type: 'json', data, raw: {} });
  const cloned = msg.clone({ deep: true });
  expect(cloned.data).not.toBe(data);
});

/* Generated by @n1k1t/unit-generator */
it('should update direction when redirect() is called', () => {
  const msg = new RequestMessage({ direction: 'incoming', type: 'plain', data: 'test', raw: {} });
  msg.redirect('outgoing');
  expect(msg.direction).toBe('outgoing');
});

/* Generated by @n1k1t/unit-generator */
it('should return plain object with expected properties in toPlain()', () => {
  const msg = new RequestMessage({ direction: 'incoming', type: 'plain', data: 'test', raw: {}, timestamp: 12345 });
  expect(msg.toPlain()).toEqual({ direction: 'incoming', type: 'plain', data: 'test', timestamp: 12345 });
});

/* Generated by @n1k1t/unit-generator */
it('should return cache object with base64 raw data in toCache()', () => {
  const rawData = Buffer.from('abc');
  const msg = new RequestMessage({
    direction: 'incoming',
    type: 'plain',
    data: 'test',
    raw: { data: rawData },
    timestamp: 123,
  });
  expect(msg.toCache().raw.data).toBe(rawData.toString('base64'));
});

/* Generated by @n1k1t/unit-generator */
it('should build from plain object using static build()', () => {
  const plain = { direction: 'outgoing' as const, type: 'json' as const, data: { x: 1 }, timestamp: 999 };
  const msg = RequestMessage.build(plain);
  expect(msg.timestamp).toBe(999);
});

/* Generated by @n1k1t/unit-generator */
it('should return true when the type matches in the is method', () => {
  const message = new RequestMessage({
    direction: 'incoming' as const,
    type: 'json' as const,
    data: { key: faker.lorem.word() },
    raw: {},
  });

  expect(message.is('json')).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('should return false when the type does not match in the is method', () => {
  const message = new RequestMessage({
    direction: 'incoming' as const,
    type: 'json' as const,
    data: {},
    raw: {},
  });

  expect(message.is('plain')).toBe(false);
});

/* Generated by @n1k1t/unit-generator */
it('should return true when checking is("plain") on a plain message', () => {
  const message = new RequestMessage({
    direction: 'outgoing' as const,
    type: 'plain' as const,
    data: faker.lorem.sentence(),
    raw: {},
  });

  expect(message.is('plain')).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('should set the direction correctly when building from a plain object', () => {
  const message = RequestMessage.build({
    direction: 'outgoing' as const,
    type: 'plain' as const,
    timestamp: faker.number.int(),
    data: faker.lorem.sentence(),
  });

  expect(message.direction).toBe('outgoing');
});

/* Generated by @n1k1t/unit-generator */
it('should set the raw data to an empty object when building from a plain object', () => {
  const message = RequestMessage.build({
    direction: 'incoming' as const,
    type: 'json' as const,
    timestamp: faker.number.int(),
    data: {},
  });

  expect(message.raw).toEqual({});
});

/* Generated by @n1k1t/unit-generator */
it('should set the direction correctly when building from direction and predicate', () => {
  const message = RequestMessage.build('incoming' as const, faker.lorem.sentence());
  expect(message.direction).toBe('incoming');
});

/* Generated by @n1k1t/unit-generator */
it('should set the direction correctly when building from direction only', () => {
  const message = RequestMessage.build('outgoing' as const, faker.lorem.sentence());
  expect(message.direction).toBe('outgoing');
});
