import { RequestMessage } from './message';

/* Generated by @n1k1t/unit-generator */
it('should return true when calling is with "json" on a json message', () =>
  expect(RequestMessage.build('incoming', {}).is('json')).toBe(true));

/* Generated by @n1k1t/unit-generator */
it('should return false when calling is with "plain" on a json message', () =>
  expect(RequestMessage.build('incoming', {}).is('plain')).toBe(false));

/* Generated by @n1k1t/unit-generator */
it('should serialize object data to JSON buffer when dataRaw is unchanged', () =>
  expect(RequestMessage.build('incoming', { a: 1 }).serialize()).toEqual(Buffer.from('{"a":1}')));

/* Generated by @n1k1t/unit-generator */
it('should serialize string data to Buffer when dataRaw is unchanged', () =>
  expect(RequestMessage.build('incoming', 'hello').serialize()).toEqual(Buffer.from('hello')));

/* Generated by @n1k1t/unit-generator */
it('should return dataRaw in serialize if data is undefined and dataRaw is unchanged', () => {
  const msg = RequestMessage.build({
    direction: 'incoming',
    type: 'plain',
    timestamp: Date.now(),
    data: undefined,
    dataRaw: 'raw',
  });
  expect(msg.serialize()).toEqual(Buffer.from('raw'));
});

/* Generated by @n1k1t/unit-generator */
it('should return modified dataRaw in serialize even if data is an object', () => {
  const msg = RequestMessage.build('incoming', { a: 1 });
  msg.dataRaw = Buffer.from('new');
  expect(msg.serialize()).toEqual(Buffer.from('new'));
});

/* Generated by @n1k1t/unit-generator */
it('should return a new instance when calling clone', () => {
  const msg = RequestMessage.build('incoming', 'b');
  expect(msg.clone()).not.toBe(msg);
});

/* Generated by @n1k1t/unit-generator */
it('should deep clone object data when calling clone', () => {
  const data = { a: 1 };
  const msg = RequestMessage.build('incoming', data);
  expect(msg.clone().data).not.toBe(data);
});

/* Generated by @n1k1t/unit-generator */
it('should maintain data values when calling clone', () =>
  expect(RequestMessage.build('incoming', { a: 1 }).clone().data).toEqual({ a: 1 }));

/* Generated by @n1k1t/unit-generator */
it('should build a json message when predicate is an object', () =>
  expect(RequestMessage.build('incoming', { a: 1 }).type).toBe('json'));

/* Generated by @n1k1t/unit-generator */
it('should set data to the provided object when building from an object', () => {
  const obj = { a: 1 };
  expect(RequestMessage.build('incoming', obj).data).toStrictEqual(obj);
});

/* Generated by @n1k1t/unit-generator */
it('should set dataRaw to stringified object when building from an object', () =>
  expect(RequestMessage.build('incoming', { a: 1 }).dataRaw).toEqual(Buffer.from('{"a":1}')));

/* Generated by @n1k1t/unit-generator */
it('should build a json message when predicate is a Buffer containing valid JSON', () =>
  expect(RequestMessage.build('incoming', Buffer.from('{"a":1}')).type).toBe('json'));

/* Generated by @n1k1t/unit-generator */
it('should set data to parsed result when building from valid JSON Buffer', () =>
  expect(RequestMessage.build('incoming', Buffer.from('{"a":1}')).data).toEqual({ a: 1 }));

/* Generated by @n1k1t/unit-generator */
it('should set dataRaw to the provided Buffer when building from a Buffer', () => {
  const buf = Buffer.from('test');
  expect(RequestMessage.build('incoming', buf).dataRaw).toBe(buf);
});

/* Generated by @n1k1t/unit-generator */
it('should build a plain message when predicate is a non-json string', () =>
  expect(RequestMessage.build('incoming', 'hello world').type).toBe('plain'));

/* Generated by @n1k1t/unit-generator */
it('should set data to original string when building from a non-json string', () => {
  expect(RequestMessage.build('incoming', 'test').data).toBe('test');
});

/* Generated by @n1k1t/unit-generator */
it('should set dataRaw to Buffer of string when building from a string', () =>
  expect(RequestMessage.build('incoming', 'test').dataRaw).toEqual(Buffer.from('test')));
