import { cast, wait, buildCounter, serializeRegExp, parseJsonSafe, formatHeaders, cut } from './common';

/* Generated by @n1k1t/unit-generator */
it('cast should return the same value', () => {
  expect(cast({ a: 1 })).toEqual({ a: 1 });
});

/* Generated by @n1k1t/unit-generator */
it('wait should have a value property equal to the provided milliseconds', () => {
  expect(wait(100).value).toBe(100);
});

/* Generated by @n1k1t/unit-generator */
it('wait should resolve after the specified time', async () => {
  jest.useFakeTimers();
  const promise = wait(10);
  jest.advanceTimersByTime(10);
  await expect(promise).resolves.toBeUndefined();
  jest.useRealTimers();
});

/* Generated by @n1k1t/unit-generator */
it('buildCounter should return a function that increments from initial value', () => {
  const counter = buildCounter(10);
  expect(counter()).toBe(11);
});

/* Generated by @n1k1t/unit-generator */
it('buildCounter should use the provided step', () => {
  const counter = buildCounter(0, 5);
  expect(counter()).toBe(5);
});

/* Generated by @n1k1t/unit-generator */
it('buildCounter should use the value passed to the returned function as step', () => {
  const counter = buildCounter(0, 1);
  expect(counter(10)).toBe(10);
});

/* Generated by @n1k1t/unit-generator */
it('serializeRegExp should return an object with source and flags', () => {
  expect(serializeRegExp(/abc/g)).toEqual({ source: 'abc', flags: 'g' });
});

/* Generated by @n1k1t/unit-generator */
it('parseJsonSafe should return status OK and the parsed result for valid JSON', () => {
  expect(parseJsonSafe('{"a":1}')).toEqual({ status: 'OK', result: { a: 1 } });
});

/* Generated by @n1k1t/unit-generator */
it('parseJsonSafe should return status ERROR for invalid JSON', () => {
  expect(parseJsonSafe('invalid').status).toBe('ERROR');
});

/* Generated by @n1k1t/unit-generator */
it('parseJsonSafe should return an Error instance on failure', () => {
  expect((parseJsonSafe('invalid') as any).error).toBeInstanceOf(Error);
});

/* Generated by @n1k1t/unit-generator */
it('formatHeaders should lowercase all keys', () => {
  expect(formatHeaders({ 'Content-Type': 'application/json' })).toEqual({ 'content-type': 'application/json' });
});

/* Generated by @n1k1t/unit-generator */
it('formatHeaders should join array values with a comma', () => {
  expect(formatHeaders({ Accept: ['text/html', 'application/xhtml+xml'] })['accept']).toBe(
    'text/html,application/xhtml+xml',
  );
});

/* Generated by @n1k1t/unit-generator */
it('formatHeaders should convert numeric values to strings', () => {
  expect(formatHeaders({ 'X-Count': 123 })['x-count']).toBe('123');
});

/* Generated by @n1k1t/unit-generator */
it('cut should split a string into chunks of the specified length', () => {
  expect(cut('123456', 3)).toEqual(['123', '456']);
});

/* Generated by @n1k1t/unit-generator */
it('cut should handle strings that are not multiples of the length', () => {
  expect(cut('12345', 2)).toEqual(['12', '34', '5']);
});

/* Generated by @n1k1t/unit-generator */
it('should call clearTimeout when the abort method is called', () => {
  const spy = jest.spyOn(global, 'clearTimeout');
  const waiter = wait(10);
  waiter.abort();
  expect(spy).toHaveBeenCalled();
  spy.mockRestore();
});
