import { faker } from '@faker-js/faker';
import { Container } from './model';

it('should initialize Container with correct properties', () => {
  const provided = {
    key: faker.string.uuid(),
    group: faker.lorem.word(),
    payload: { data: faker.lorem.sentence() },
    ttl: faker.number.int({ min: 1, max: 1000 }),
    timestamp: Date.now(),
  };
  const container = new Container(provided);

  expect(container).toMatchObject({
    key: provided.key,
    group: provided.group,
    payload: provided.payload,
    ttl: provided.ttl,
    timestamp: provided.timestamp,
  });
});

// Test generated using Keploy
it('should merge payload correctly', () => {
  const initialData = faker.lorem.word();
  const newData = faker.lorem.word();
  const container = new Container({
    key: faker.string.uuid(),
    group: 'test',
    payload: { data: initialData },
    ttl: 60,
    timestamp: Date.now(),
  });

  container.merge({ data: newData });

  expect(container.payload.data).toBe(newData);
});

// Test generated using Keploy
it('should assign new payload to Container', () => {
  const initialData = faker.lorem.word();
  const newData = faker.lorem.word();
  const container = new Container({
    key: faker.string.uuid(),
    group: 'test',
    payload: { data: initialData },
    ttl: 60,
    timestamp: Date.now(),
  });

  container.assign({ data: newData });

  expect(container.payload.data).toBe(newData);
});

// Test generated using Keploy
it('should call onBind hook when binding', () => {
  const onBindMock = jest.fn();
  const container = new Container({
    key: faker.string.uuid(),
    group: 'test',
    payload: {},
    ttl: 60,
    timestamp: Date.now(),
    hooks: {
      bind: onBindMock,
    },
  });

  container.bind(faker.string.uuid());

  expect(onBindMock).toHaveBeenCalled();
});

// Test generated using Keploy
it('should call onUnbind hook when unbinding', () => {
  const onUnbindMock = jest.fn();
  const container = new Container({
    key: faker.string.uuid(),
    group: 'test',
    payload: {},
    ttl: 60,
    timestamp: Date.now(),
    hooks: {
      unbind: onUnbindMock,
    },
  });

  container.unbind();

  expect(onUnbindMock).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('merge replaces arrays when merging', () => {
  const container = Container.build({
    key: faker.string.uuid(),
    group: 'test',
    payload: { items: [faker.number.int(), faker.number.int()] },
    ttl: 5,
    timestamp: 0,
  });
  const newItem = faker.number.int();

  container.merge({ items: [newItem] });

  expect(container.payload.items).toEqual([newItem]);
});

/* Generated by @n1k1t/unit-generator */
it('clone deep clones payload', () => {
  const container = Container.build({
    key: faker.string.uuid(),
    group: 'test',
    payload: { nested: { a: faker.number.int() } },
    ttl: 5,
    timestamp: 0,
  });

  const cloned = container.clone();

  expect(cloned.payload.nested).not.toBe(container.payload.nested);
});
