import { Value } from '@n1k1t/typebox/value';
import { compileContainerLink } from './utils';

/* Generated by @n1k1t/unit-generator */
it('should return the string itself when key is a string', () => {
  const key = 'testString';
  expect(compileContainerLink(key)).toEqual(key);
});

/* Generated by @n1k1t/unit-generator */
it('should return the hash of the object as a string when key is an object', () => {
  const key = { id: 1, name: 'test' };
  expect(compileContainerLink(key)).toEqual(Value.Hash(key).toString());
});
