import { WebSocketFactory } from './factory';
import { WebSocket } from './model';

/* Generated by @n1k1t/unit-generator */
it('should create a WebSocketFactory instance using build method', () => {
  expect(WebSocketFactory.build({})).toBeInstanceOf(WebSocketFactory);
});

/* Generated by @n1k1t/unit-generator */
it('should store configuration in the factory instance', () => {
  const configuration = { url: 'ws://localhost' };
  const factory = new WebSocketFactory(configuration);
  expect(factory.configuration).toEqual(configuration);
});

/* Generated by @n1k1t/unit-generator */
it('should compile and return a WebSocket instance', () => {
  const factory = new WebSocketFactory({ url: 'ws://localhost' });
  expect(factory.compile()).toBeInstanceOf(WebSocket);
});

/* Generated by @n1k1t/unit-generator */
it('should merge configurations when compiling', () => {
  const factory = new WebSocketFactory({ baseURL: 'ws://localhost' });
  const ws = factory.compile({ url: 'path' });
  expect(ws.url).toBe('ws://localhost/path');
});

/* Generated by @n1k1t/unit-generator */
it('should prioritize signal from compile argument over factory configuration', () => {
  const signal1 = new AbortController().signal;
  const signal2 = new AbortController().signal;
  const factory = new WebSocketFactory({ url: 'ws://localhost', signal: signal1 });
  const ws = factory.compile({ signal: signal2 });
  expect(ws.configuration.signal).toBe(signal2);
});

/* Generated by @n1k1t/unit-generator */
it('should use factory signal if compile argument signal is missing', () => {
  const signal = new AbortController().signal;
  const factory = new WebSocketFactory({ url: 'ws://localhost', signal });
  const ws = factory.compile({});
  expect(ws.configuration.signal).toBe(signal);
});

/* Generated by @n1k1t/unit-generator */
it('should deep merge query parameters from factory and compile arguments', () => {
  const factory = new WebSocketFactory({ url: 'ws://localhost', query: { a: '1' } });
  const ws = factory.compile({ query: { b: '2' } });
  expect(ws.configuration.query).toEqual({ a: '1', b: '2' });
});

/* Generated by @n1k1t/unit-generator */
it('should not mutate the factory configuration when compiling', () => {
  const config = { url: 'ws://localhost' };
  const factory = new WebSocketFactory(config);
  factory.compile({ timeout: 1000 });
  expect(factory.configuration).toEqual({ url: 'ws://localhost' });
});

/* Generated by @n1k1t/unit-generator */
it('should throw error if url is missing in both factory and compile configurations', () => {
  const factory = new WebSocketFactory({});
  expect(() => factory.compile()).toThrow('[url] is invalid');
});
