import { WebSocketConnectionError } from './errors';
import { WebSocket } from './model';

/* Generated by @n1k1t/unit-generator */
it('should throw an error if both url and baseURL are missing in build method', () => {
  expect(() => WebSocket.build({})).toThrow('[url] is invalid');
});

/* Generated by @n1k1t/unit-generator */
it('should construct the correct URL with baseURL and url', () => {
  const ws = WebSocket.build({ baseURL: 'http://localhost', url: 'path' });
  expect(ws.url).toBe('http://localhost/path');
});

/* Generated by @n1k1t/unit-generator */
it('should construct the correct URL with baseURL and query', () => {
  const ws = WebSocket.build({ baseURL: 'ws://localhost', query: { a: '1' } });
  expect(ws.url).toBe('ws://localhost?a=1');
});

/* Generated by @n1k1t/unit-generator */
it('should return false for checkIsConnected when source is not initialized', () => {
  const ws = new WebSocket('ws://localhost', {});
  expect(ws.checkIsConnected()).toBe(false);
});

/* Generated by @n1k1t/unit-generator */
it('should return true for checkIsConnected when readyState is 1', () => {
  const ws = new WebSocket('ws://localhost', {});
  (ws as any).nested.source = { readyState: 1 };
  expect(ws.checkIsConnected()).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('should return false for checkIsConnected when readyState is not 1', () => {
  const ws = new WebSocket('ws://localhost', {});
  (ws as any).nested.source = { readyState: 0 };
  expect(ws.checkIsConnected()).toBe(false);
});

/* Generated by @n1k1t/unit-generator */
it('should return the error from the nested state', () => {
  const ws = new WebSocket('ws://localhost', {});
  const error = new Error('test error') as any;
  (ws as any).nested.error = error;
  expect(ws.error).toBe(error);
});

/* Generated by @n1k1t/unit-generator */
it('should set the status when close is called', () => {
  const ws = new WebSocket('ws://localhost', {});
  ws.close(1000);
  expect((ws as any).nested.status).toBe(1000);
});

/* Generated by @n1k1t/unit-generator */
it('should return the headers immediately if they are already set', async () => {
  const ws = new WebSocket('ws://localhost', {});
  const headers = { 'content-type': 'application/json' };
  (ws as any).nested.headers = headers;
  const result = await ws.headers();
  expect(result).toBe(headers);
});

/* Generated by @n1k1t/unit-generator */
it('should return the status immediately if it is already set', async () => {
  const ws = new WebSocket('ws://localhost', {});
  (ws as any).nested.status = 1000;
  const status = await ws.status();
  expect(status).toBe(1000);
});

/* Generated by @n1k1t/unit-generator */
it('should subscribe to the observable when subscribe is called', () => {
  const ws = new WebSocket('ws://localhost', {});
  const next = jest.fn();
  ws.subscribe({ next });
  ws.observable.next('test' as any);
  expect(next).toHaveBeenCalledWith('test');
});

/* Generated by @n1k1t/unit-generator */
it('should resolve waitUntilComplete when the observable completes', async () => {
  const ws = new WebSocket('ws://localhost', {});
  const promise = ws.waitUntilComplete();
  ws.observable.complete();
  await expect(promise).resolves.toBeUndefined();
});

/* Generated by @n1k1t/unit-generator */
it('should call the handler for each message in forEach', async () => {
  const ws = new WebSocket('ws://localhost', {});
  const messages: any[] = [];
  const promise = ws.forEach((msg) => messages.push(msg));
  ws.observable.next('msg1' as any);
  ws.observable.complete();
  await promise;
  expect(messages).toEqual(['msg1']);
});

/* Generated by @n1k1t/unit-generator */
it('should throw an error if send is called before connect', async () => {
  const ws = new WebSocket('ws://localhost', {});
  await expect(ws.send('data')).rejects.toThrow();
});

/* Generated by @n1k1t/unit-generator */
it('should resolve headers when upgrade event is emitted on source', async () => {
  const ws = new WebSocket('ws://localhost', {});
  const mockSource = { once: jest.fn() };
  (ws as any).nested.source = mockSource;
  const promise = ws.headers();
  const callback = mockSource.once.mock.calls.find((call: any) => call[0] === 'upgrade')[1];
  callback({ headers: { 'x-foo': 'bar' } });
  expect(await promise).toEqual({ 'x-foo': 'bar' });
});

/* Generated by @n1k1t/unit-generator */
it('should resolve status when close event is emitted on source', async () => {
  const ws = new WebSocket('ws://localhost', {});
  const mockSource = { once: jest.fn() };
  (ws as any).nested.source = mockSource;
  const promise = ws.status();
  const callback = mockSource.once.mock.calls.find((call: any) => call[0] === 'close')[1];
  callback(1006);
  expect(await promise).toBe(1006);
});

/* Generated by @n1k1t/unit-generator */
it('should resolve status when source emits close event', async () => {
  const ws = new WebSocket('ws://localhost', {});
  const mockSource = { once: jest.fn() } as any;
  (ws as any).nested.source = mockSource;
  const promise = ws.status();
  const closeHandler = mockSource.once.mock.calls.find((call: any) => call[0] === 'close')[1];
  closeHandler(1001);
  await expect(promise).resolves.toBe(1001);
});

/* Generated by @n1k1t/unit-generator */
it('should throw WebSocketConnectionError in send if readyState is not 1', async () => {
  const ws = new WebSocket('ws://localhost', {});
  (ws as any).nested.source = { readyState: 0, CONNECTING: 0 };
  await expect(ws.send('data')).rejects.toThrow(WebSocketConnectionError);
});

/* Generated by @n1k1t/unit-generator */
it('should reject send if source.send returns an error', async () => {
  const ws = new WebSocket('ws://localhost', {});
  const mockSource = { readyState: 1, send: jest.fn((p, cb: any) => cb(new Error('send failed'))), CONNECTING: 0 };
  (ws as any).nested.source = mockSource;
  await expect(ws.send('data')).rejects.toThrow('send failed');
});

/* Generated by @n1k1t/unit-generator */
it('should handle abort signal immediately if already aborted in connect', () => {
  const controller = new AbortController();
  controller.abort();
  const ws = new WebSocket('ws://localhost', { signal: controller.signal });
  const closeSpy = jest.spyOn(ws, 'close');
  ws.connect();
  expect(closeSpy).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should add abort listener if signal is provided but not aborted', () => {
  const controller = new AbortController();
  const ws = new WebSocket('ws://localhost', { signal: controller.signal });
  const addSpy = jest.spyOn(controller.signal, 'addEventListener');
  ws.connect();
  expect(addSpy).toHaveBeenCalledWith('abort', expect.any(Function));
});

/* Generated by @n1k1t/unit-generator */
it('should set nested error if WebSocketOriginal constructor throws', () => {
  jest.spyOn(require('ws'), 'WebSocket').mockImplementationOnce(() => {
    throw new Error('init error');
  });
  const ws = new WebSocket('ws://localhost', {}).connect();
  expect(ws.error).toBeInstanceOf(WebSocketConnectionError);
});

/* Generated by @n1k1t/unit-generator */
it('should complete observable via setImmediate in close method', (done) => {
  const ws = new WebSocket('ws://localhost', {});
  ws.observable.subscribe({
    complete: () => {
      expect(true).toBe(true);
      done();
    },
  });
  ws.close();
});

/* Generated by @n1k1t/unit-generator */
it('should throw error in resolve if source is null', async () => {
  const ws = new WebSocket('ws://localhost', {});
  await expect((ws as any).resolve()).rejects.toThrow(WebSocketConnectionError);
});

/* Generated by @n1k1t/unit-generator */
it('should return null in resolve if signal is aborted', async () => {
  const controller = new AbortController();
  controller.abort();
  const ws = new WebSocket('ws://localhost', { signal: controller.signal });
  (ws as any).nested.source = { readyState: 1 } as any;
  const result = await (ws as any).resolve();
  expect(result).toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('should throw WebSocketConnectionError if source emits error during resolve', async () => {
  const ws = new WebSocket('ws://localhost', {});
  const mockSource = {
    readyState: 0,
    CONNECTING: 0,
    once: jest.fn((e, cb) => {
      if (e === 'error') cb(new Error('fail'));
    }),
  };
  (ws as any).nested.source = mockSource;
  await expect((ws as any).resolve()).rejects.toThrow(WebSocketConnectionError);
});

/* Generated by @n1k1t/unit-generator */
it('should throw error in handleAbortSignal if source is missing', () => {
  const ws = new WebSocket('ws://localhost', {});
  expect(() => (ws as any).handleAbortSignal()).toThrow('Connection was not estabilished');
});

/* Generated by @n1k1t/unit-generator */
it('should throw error in scheduleConnectionClosing if source is missing', async () => {
  const ws = new WebSocket('ws://localhost', {});
  await expect((ws as any).scheduleConnectionClosing()).rejects.toThrow('Connection was not estabilished');
});

/* Generated by @n1k1t/unit-generator */
it('should return null in scheduleConnectionClosing if timeout is not set', async () => {
  const ws = new WebSocket('ws://localhost', {});
  (ws as any).nested.source = { readyState: 1 } as any;
  const result = await (ws as any).scheduleConnectionClosing();
  expect(result).toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('should throw error in build if url and baseURL are missing', () => {
  expect(() => WebSocket.build({} as any)).toThrow('[url] is invalid');
});
