import { ClientMethod } from './method';

/* Generated by @n1k1t/unit-generator */
it('should create an instance of ClientMethod when build is called', () => {
  expect(ClientMethod.build()).toBeInstanceOf(ClientMethod);
});

/* Generated by @n1k1t/unit-generator */
it('should return the ClientMethod instance when register is called', () => {
  const method = ClientMethod.build();
  const result = method.register('remote', () => () => Promise.resolve({}));
  expect(result).toBe(method);
});

/* Generated by @n1k1t/unit-generator */
it('should return a function when compile is called', () => {
  const method = ClientMethod.build();
  const handler = method.compile('remote', {} as any);
  expect(typeof handler).toBe('function');
});

/* Generated by @n1k1t/unit-generator */
it('should reject with "Not implemented" by default for remote handler', async () => {
  const method = ClientMethod.build();
  const handler = method.compile('remote', {} as any);
  await expect(handler({})).rejects.toThrow('Not implemented');
});

/* Generated by @n1k1t/unit-generator */
it('should reject with "Not implemented" by default for onsite handler', async () => {
  const method = ClientMethod.build();
  const handler = method.compile('onsite', {} as any);
  await expect(handler({})).rejects.toThrow('Not implemented');
});

/* Generated by @n1k1t/unit-generator */
it('should update the remote handler when register is called', async () => {
  const method = ClientMethod.build();
  method.register('remote', () => () => Promise.resolve('remote-val'));
  const result = await method.compile('remote', {} as any)({});
  expect(result).toBe('remote-val');
});

/* Generated by @n1k1t/unit-generator */
it('should update the onsite handler when register is called', async () => {
  const method = ClientMethod.build();
  method.register('onsite', () => () => Promise.resolve('onsite-val'));
  const result = await method.compile('onsite', {} as any)({});
  expect(result).toBe('onsite-val');
});

/* Generated by @n1k1t/unit-generator */
it('should pass the context to the handler during compile', () => {
  const method = ClientMethod.build();
  let capturedContext: any;
  method.register('remote', (ctx) => {
    capturedContext = ctx;
    return () => Promise.resolve({});
  });
  const context = { id: 'ctx-123' };
  method.compile('remote', context as any);
  expect(capturedContext).toBe(context);
});

/* Generated by @n1k1t/unit-generator */
it('should pass the incoming data to the compiled handler', async () => {
  const method = ClientMethod.build();
  let capturedIncoming: any;
  method.register('remote', () => (incoming) => {
    capturedIncoming = incoming;
    return Promise.resolve({});
  });
  const handler = method.compile('remote', {} as any);
  await handler({ data: 'test' });
  expect(capturedIncoming).toEqual({ data: 'test' });
});
