import { OnsiteClient } from './onsite';
import { Client } from './models';

import * as methods from './methods';

/* Generated by @n1k1t/unit-generator */
it('should return an instance of OnsiteClient when calling build', () => {
  const provider = {} as any;
  const client = OnsiteClient.build(provider);
  expect(client).toBeInstanceOf(OnsiteClient);
});

/* Generated by @n1k1t/unit-generator */
it('should call compile on methods with "onsite" and provider during construction', () => {
  const provider = {} as any;
  const spy = jest.spyOn(methods.ping, 'compile');
  new OnsiteClient(provider);
  expect(spy).toHaveBeenCalledWith('onsite', provider);
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should call expectationsGroupUpdate method with correct body', async () => {
  const provider = {} as any;
  const client = new OnsiteClient(provider);
  const mockFn = jest.fn().mockResolvedValue([]);
  (client as any).methods.expectationsGroupUpdate = mockFn;
  const body = [{ id: '1', set: {} }];
  await client.updateExpectationsGroup(body as any);
  expect(mockFn).toHaveBeenCalledWith({ set: body });
});

/* Generated by @n1k1t/unit-generator */
it('should return the result of expectationsGroupUpdate', async () => {
  const provider = {} as any;
  const client = new OnsiteClient(provider);
  const expected = [{ id: '1' }];
  const mockFn = jest.fn().mockResolvedValue(expected);
  (client as any).methods.expectationsGroupUpdate = mockFn;
  const result = await client.updateExpectationsGroup([] as any);
  expect(result).toBe(expected);
});

/* Generated by @n1k1t/unit-generator */
it('should be an instance of Client', () => {
  const provider = {} as any;
  const client = new OnsiteClient(provider);
  expect(client).toBeInstanceOf(Client);
});

/* Generated by @n1k1t/unit-generator */
it('should populate methods property with compiled functions', () => {
  const provider = {} as any;
  const client = new OnsiteClient(provider);
  expect(typeof (client as any).methods.ping).toBe('function');
});
