import axios from 'axios';

import { RemoteClient } from './remote';
import * as methods from './methods';

/* Generated by @n1k1t/unit-generator */
it('should call axios.create with provided baseUrl and timeout', () => {
  const axiosSpy = jest.spyOn(axios, 'create').mockReturnValue({} as any);
  const options = { baseUrl: 'http://localhost:3000', timeout: 5000 };
  new RemoteClient(options);
  expect(axiosSpy).toHaveBeenCalledWith({
    baseURL: options.baseUrl,
    timeout: options.timeout,
  });
  axiosSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should use default timeout of 10 seconds if not provided in options', () => {
  const axiosSpy = jest.spyOn(axios, 'create').mockReturnValue({} as any);
  new RemoteClient({ baseUrl: 'http://localhost:3000' });
  expect(axiosSpy).toHaveBeenCalledWith(
    expect.objectContaining({
      timeout: 10000,
    }),
  );
  axiosSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should compile all methods from the methods module during construction', () => {
  jest.spyOn(axios, 'create').mockReturnValue({} as any);
  const pingSpy = jest.spyOn(methods.ping, 'compile').mockReturnValue(jest.fn());
  const options = { baseUrl: 'http://localhost:3000' };
  new RemoteClient(options);
  expect(pingSpy).toHaveBeenCalledWith('remote', expect.anything());
  pingSpy.mockRestore();
  jest.restoreAllMocks();
});

/* Generated by @n1k1t/unit-generator */
it('should return the compiled expectationsGroupUpdate method via updateExpectationsGroup getter', () => {
  jest.spyOn(axios, 'create').mockReturnValue({} as any);
  const mockCompiled = jest.fn();
  const spy = jest.spyOn(methods.expectationsGroupUpdate, 'compile').mockReturnValue(mockCompiled);
  const client = new RemoteClient({ baseUrl: 'http://localhost:3000' });
  expect(client.updateExpectationsGroup).toBe(mockCompiled);
  spy.mockRestore();
  jest.restoreAllMocks();
});

/* Generated by @n1k1t/unit-generator */
it('should return the compiled providersCreate method via createProvider getter', () => {
  jest.spyOn(axios, 'create').mockReturnValue({} as any);
  const mockCompiled = jest.fn();
  const spy = jest.spyOn(methods.providersCreate, 'compile').mockReturnValue(mockCompiled);
  const client = new RemoteClient({ baseUrl: 'http://localhost:3000' });
  expect(client.createProvider).toBe(mockCompiled);
  spy.mockRestore();
  jest.restoreAllMocks();
});

/* Generated by @n1k1t/unit-generator */
it('should return the compiled providersDelete method via deleteProvider getter', () => {
  jest.spyOn(axios, 'create').mockReturnValue({} as any);
  const mockCompiled = jest.fn();
  const spy = jest.spyOn(methods.providersDelete, 'compile').mockReturnValue(mockCompiled);
  const client = new RemoteClient({ baseUrl: 'http://localhost:3000' });
  expect(client.deleteProvider).toBe(mockCompiled);
  spy.mockRestore();
  jest.restoreAllMocks();
});

/* Generated by @n1k1t/unit-generator */
it('should call ping and return a RemoteClient instance in the static connect method', async () => {
  jest.spyOn(axios, 'create').mockReturnValue({} as any);
  const pingMock = jest.fn().mockResolvedValue('pong');
  const spy = jest.spyOn(methods.ping, 'compile').mockReturnValue(pingMock);
  const options = { baseUrl: 'http://localhost:3000' };
  const client = await RemoteClient.connect(options);
  expect(pingMock).toHaveBeenCalled();
  expect(client).toBeInstanceOf(RemoteClient);
  spy.mockRestore();
  jest.restoreAllMocks();
});

/* Generated by @n1k1t/unit-generator */
it('should store the provided options in the instance', () => {
  jest.spyOn(axios, 'create').mockReturnValue({} as any);
  const options = { baseUrl: 'http://localhost:3000', timeout: 1234 };
  const client = new RemoteClient(options);
  expect(client.options).toEqual(options);
  jest.restoreAllMocks();
});
