import { compileExpectationOperators } from './expectations';

/* Generated by @n1k1t/unit-generator */
it('should return an object with $not property when calling not()', () => {
  expect(compileExpectationOperators().not(<any>{ foo: 'bar' })).toEqual({ $not: { foo: 'bar' } });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $and property when calling and()', () => {
  expect(compileExpectationOperators().and(<any>[{ foo: 'bar' }])).toEqual({ $and: [{ foo: 'bar' }] });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $or property when calling or()', () => {
  expect(compileExpectationOperators().or(<any>[{ foo: 'bar' }])).toEqual({ $or: [{ foo: 'bar' }] });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $exec property when calling exec()', () => {
  const fn = () => true;
  expect(compileExpectationOperators().exec(fn)).toEqual({ $exec: fn });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $if property when calling if()', () => {
  const command: any = { $exec: () => true, $then: {} };
  expect(compileExpectationOperators().if(command)).toEqual({ $if: command });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $switch property and $location when calling switch() with object predicate', () => {
  expect(compileExpectationOperators().switch('body' as any, { $cases: {} })).toEqual({
    $switch: {
      $location: 'body',
      $cases: {},
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $switch property, $location and $path when calling switch() with $path predicate', () => {
  expect(compileExpectationOperators().switch('body' as any, '$path', 'foo.bar', { $cases: {} })).toEqual({
    $switch: {
      $location: 'body',
      $path: 'foo.bar',
      $cases: {},
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $switch property, $location and $exec when calling switch() with $exec predicate', () => {
  const fn = () => 'val';
  expect(compileExpectationOperators().switch('body' as any, '$exec', fn, { $cases: {} })).toEqual({
    $switch: {
      $location: 'body',
      $exec: fn,
      $cases: {},
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $has property and $location when calling has() with object predicate', () => {
  expect(compileExpectationOperators().has('body' as any, <any>{ $exists: true })).toEqual({
    $has: {
      $location: 'body',
      $exists: true,
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $has property, $location and $path when calling has() with $path predicate', () => {
  expect(compileExpectationOperators().has('body' as any, '$path', 'foo.bar', <any>{ $exists: true })).toEqual({
    $has: {
      $location: 'body',
      $path: 'foo.bar',
      $exists: true,
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $has property, $location and $jsonPath when calling has() with $jsonPath predicate', () => {
  expect(compileExpectationOperators().has('body' as any, '$jsonPath', '$.foo', <any>{ $exists: true })).toEqual({
    $has: {
      $location: 'body',
      $jsonPath: '$.foo',
      $exists: true,
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $has property and $location when calling has() without command', () => {
  expect(compileExpectationOperators().has('body' as any)).toEqual({
    $has: {
      $location: 'body',
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $set property and $location when calling set() with object predicate', () => {
  expect(compileExpectationOperators().set('body' as any, <any>{ value: 1 })).toEqual({
    $set: {
      $location: 'body',
      value: 1,
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $set property, $location and $path when calling set() with $path predicate', () => {
  expect(compileExpectationOperators().set('body' as any, '$path', 'foo.bar', <any>{ value: 1 })).toEqual({
    $set: {
      $location: 'body',
      $path: 'foo.bar',
      value: 1,
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $set property, $location and $jsonPath when calling set() with $jsonPath predicate', () => {
  expect(compileExpectationOperators().set('body' as any, '$jsonPath', '$.foo', <any>{ value: 1 })).toEqual({
    $set: {
      $location: 'body',
      $jsonPath: '$.foo',
      value: 1,
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $merge property and $location when calling merge() with object predicate', () => {
  expect(compileExpectationOperators().merge('body' as any, <any>{ value: {} })).toEqual({
    $merge: {
      $location: 'body',
      value: {},
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $merge property, $location and $path when calling merge() with $path predicate', () => {
  expect(compileExpectationOperators().merge('body' as any, '$path', 'foo.bar', <any>{ value: {} })).toEqual({
    $merge: {
      $location: 'body',
      $path: 'foo.bar',
      value: {},
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $merge property, $location and $jsonPath when calling merge() with $jsonPath predicate', () => {
  expect(compileExpectationOperators().merge('body' as any, '$jsonPath', '$.foo', <any>{ value: {} })).toEqual({
    $merge: {
      $location: 'body',
      $jsonPath: '$.foo',
      value: {},
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $remove property and $location when calling remove() with object predicate', () => {
  expect(compileExpectationOperators().remove('body' as any, { $path: 'foo' })).toEqual({
    $remove: {
      $location: 'body',
      $path: 'foo',
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $remove property, $location and $path when calling remove() with $path predicate', () => {
  expect(compileExpectationOperators().remove('body' as any, '$path', 'foo.bar')).toEqual({
    $remove: {
      $location: 'body',
      $path: 'foo.bar',
    },
  });
});

/* Generated by @n1k1t/unit-generator */
it('should return an object with $remove property, $location and $jsonPath when calling remove() with $jsonPath predicate', () => {
  expect(compileExpectationOperators().remove('body' as any, '$jsonPath', '$.foo')).toEqual({
    $remove: {
      $location: 'body',
      $jsonPath: '$.foo',
    },
  });
});
